language: php
sudo: required

php:
  - '7.3'

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

before_script:
  - cd app && composer install && cd ..
  - docker-compose up -d

script:
  - sudo chmod -R 777 var/logs
  - cd app/php && php app.php -a fo1 -b bar
